# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Template to setup api gateway and apis as part of bootstrap
Parameters:
  ServerlessApiGatewayApi:
    Type: String
  HelloWorldFunctionArn:
    Type: String
Resources:
  #provide api gateway permissions to call lambda functions
  
  MonitorUsageThisMonthLambdaApiGatewayExecutionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref HelloWorldFunctionArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Join ["", ["arn:aws:execute-api:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", !Ref ServerlessApiGatewayApi, "/*/*/*" ]]  