AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Template to deploy lambda functions as part of bootstrap
# Parameters:

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../functions/HelloWorld
      Handler: hello_world.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

Outputs:
  HelloWorldFunctionArn: 
    Value: !GetAtt HelloWorldFunction.Arn