AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Template to deploy lambda functions as part of bootstrap

    
Globals:
  Function:
    Timeout: 3

Resources:
  MyLambdaRole: 
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole # for execute function
        - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy   # for show log in cloudwatch 

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      # CodeUri: ../functions/HelloWorld
      Handler: hello_world.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Role: !GetAtt MyLambdaRole.Arn

Outputs:
  HelloWorldFunctionArn: 
    Value: !GetAtt HelloWorldFunction.Arn